name: ci for testing on main and develop

on:
  push:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies ğŸ“¦
        run: npm ci
      - name: Build the app ğŸ—
        run: npm run build --if-present

      - name: Run component tests ğŸ”¸
        run: npm test

      - name: Start the app ğŸ“¤
        run: |
          npm start &
          npx wait-on --timeout 60000

  # - name: Install dependencies ğŸ“¦

#       #Using npm ci is generally faster than running npm install
#       run: |
#         cd my-app
#         npm ci
#     - name: Build the app ğŸ—
#       run: |
#         cd my-app
#         npm run build
#     - name: Run component tests ğŸ”¸
#       run: |
#         cd my-app
#         npm run test
#     - name: Start the app ğŸ“¤
#       run: |
#         cd my-app
#         npm start &
#         npx wait-on --timeout 60000
#     - name: Run visual tests ğŸ‘
#       run: |
#         cd my-app
#         npm run test:visual
